GET http://localhost:3003/api/blogs/

###

POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbWVzaSIsImlkIjoiNjJjZDIyY2QxMjU5YWQwNDcyOTNiNzg4IiwiaWF0IjoxNjU3NjEzODE4fQ.BLkvcfzfa6V4__nQxvA9mPJYeNIHxl_C3GiONJPjFvg

{
    "title": "user extractor test",
    "author": "me",
    "url": "www.sample.com",
    "likes": 89
}

###

GET http://localhost:3003/unknown/end/point/

###

PUT http://localhost:3003/api/blogs/62c8e907bc5ba9550035ebc7 HTTP/1.1
content-type: application/json

{
    "title": "test",
    "author": "me",
    "url": "www.example.com/blog",
    "likes": 16
}

###

DELETE http://localhost:3003/api/blogs/62cd4751fe2d9dadfbbc87d1 HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbWVzaSIsImlkIjoiNjJjZDIyY2QxMjU5YWQwNDcyOTNiNzg4IiwiaWF0IjoxNjU3NjEzODE4fQ.BLkvcfzfa6V4__nQxvA9mPJYeNIHxl_C3GiONJPjFvg
